export const IMAGES = {
  home: {
    hero: '/images/home/backgroundimage.png',
    community: '/images/home/csr-community.jpg',
    plantOverview: 'https://picsum.photos/seed/fipl-h3/900/650',
    team: '/images/home/careers-team.png',
    workerLeft: '/images/home/leftheroimage.png',
    workerRight: '/images/home/rightsideimage.png',
    whoWeAre: '/images/home/who-we-are.jpg',
  },
  about: {
    hero: '/images/about/hero.png',
    facility: 'https://picsum.photos/seed/fipl-a2/900/650',
    ceo: '/images/hero/FIPL6305.jpg',
  },
  plants: {
    hero: '/images/plants/hero.png',
    omoku: '/images/plants/omoku.png',
    transAmadi: '/images/plants/trans-amadi.png',
    afam: '/images/plants/afam.png',
    eleme: '/images/plants/eleme.png',
    step1: '/images/plants/step1.png',
    step2: '/images/plants/step2.png',
    step3: '/images/plants/step3.png',
    step4: '/images/plants/step4.png',
  },
  sustainability: {
    hero: '/images/sustainability/hero.png',
    nature: '/images/sustainability/nature.png',
    workplace: '/images/sustainability/safety.png',
    governance: '/images/sustainability/governance.png',
    community: '/images/sustainability/csr-community.png',
    sdg: '/images/sustainability/sdg.png',
  },
  news: {
    hero: '/images/news/hero.png',
    article1: '/images/news/article1.png',
    article2: '/images/news/article2.png',
    article3: '/images/news/article3.png',
    thumb: '/images/news/article-thumb.png',
    insight1: '/images/news/insight1.png',
    insight2: '/images/news/insight2.png',
    insight3: '/images/news/insight3.png',
  },
  careers: {
    hero: '/images/careers/hero.png',
    team: '/images/careers/team.png',
  },
  contact: {
    hero: '/images/contact/hero.png',
  },
  register: {
    hero: '/images/register/hero.png',
    vendor: '/images/register/vendor.png',
  },
} as const
