export const IMAGES = {
  home: {
    hero: '/images/home/backgroundimage.png',
    community: '/images/home/csr-community.jpg',
    plantOverview: 'https://picsum.photos/seed/fipl-h3/900/650',
    team: '/images/home/careers-team-2.jpg',
    workerLeft: '/images/home/leftheroimage.png',
    workerRight: '/images/home/rightsideimage.png',
    whoWeAre: '/images/home/who-we-are.jpg',
  },
  about: {
    hero: '/images/about/hero.png',
    facility: 'https://picsum.photos/seed/fipl-a2/900/650',
    ceo: '/images/hero/FIPL6305.jpg',
  },
  plants: {
    hero: '/images/plants/hero.png',
    omoku: ['/images/plants/omoku-1.jpg', '/images/plants/omoku-2.jpg'],
    transAmadi: [
      '/images/plants/trans-amadi-1.jpg',
      '/images/plants/trans-amadi-2.jpg',
      '/images/plants/trans-amadi-3.jpg',
    ],
    afam: [
      '/images/plants/afam-1.jpg',
      '/images/plants/afam-2.jpg',
      '/images/plants/afam-3.jpg',
      '/images/plants/afam-4.jpg',
    ],
    eleme: [
      '/images/plants/eleme-1.jpg',
      '/images/plants/eleme-2.jpg',
      '/images/plants/eleme-3.jpg',
    ],
    step1: '/images/plants/step1.png',
    step2: '/images/plants/step2.png',
    step3: '/images/plants/step3.png',
    step4: '/images/plants/step4.png',
  },
  sustainability: {
    hero: '/images/sustainability/hero.jpeg',
    nature: '/images/sustainability/governance-board.jpg',
    workplace: '/images/sustainability/health-safety.jpg',
    governance: '/images/sustainability/governance-team.jpg',
    community: '/images/sustainability/community-handover.jpg',
    sdg: '/images/sustainability/sdg.png',
    projectHealth: '/images/sustainability/csr-community.png',
    projectSchool: '/images/sustainability/ube-primary-school.jpg',
  },
  news: {
    hero: '/images/news/hero.png',
    article1: '/images/news/article1.png',
    article2: '/images/news/article2.png',
    article3: '/images/news/article3.png',
    thumb: '/images/news/article-thumb.png',
    insight1: '/images/news/insight1.png',
    insight2: '/images/news/insight2.png',
    insight3: '/images/news/insight3.png',
  },
  careers: {
    hero: '/images/careers/hero.png',
    team: '/images/careers/team.png',
  },
  contact: {
    hero: '/images/contact/hero.png',
  },
  register: {
    hero: '/images/register/hero.jpg',
    vendor: '/images/register/vendor-registration.png',
  },
} as const
